#!/bin/bash
	Wordpress()
	{
	clear
	echo "This is Wordpress $(wp core version)"
	echo "Password for $(awk -F"'" '/DB_NAME/{print $4}' wp-config.php) is $(awk -F"'" '/DB_PASSWORD/{print $4}' wp-config.php)"
	echo "mysqldump -p -u $(awk -F"'" '/DB_USER/{print $4}' wp-config.php) $(awk -F"'" '/DB_NAME/{print $4}' wp-config.php) > $(awk -F"'" '/DB_NAME/{print $4}' wp-config.php).$(whoami).$(date +%F).sql"
	ls -1t | head -1 | grep *.sql
	}
pause
	Prestashop()
	{
	clear
	if test -f "config/settings.inc.php"; then echo "This is Prestashop $(awk -F"'" '/PS_VERSION/{print $4}' config/settings.inc.php) installed on $(awk -F"'" '/PS_CREATION_DATE/{print $4}' config/settings.inc.php)" ;fi 
	echo "Password for $(awk -F"'" '/DB_NAME/{print $4}' config/settings.inc.php) is $(awk -F"'" '/DB_PASSWD_/{print $4}' config/settings.inc.php)"
	echo "mysqldump -p -u $(awk -F"'" '/DB_USER/{print $4}' config/settings.inc.php) $(awk -F"'" '/DB_NAME/{print $4}' config/settings.inc.php) > $(awk -F"'" '/DB_NAME/{print $4}' config/settings.inc.php).$(whoami).$(date +%F).sql"
	ls -1t | head -1 | grep *.sql
	}
pause
	Joomla()
	{
	clear
	if test -f "configuration.php"; then echo "This is Joomla. I got nothin ¯\_(ツ)_/¯ " ;fi
	}
pause	
	Moodle()
	{
	clear
	if test -f "moodle/config.php"; then echo "This is Moodle. I got nothin yet ¯\_(ツ)_/¯ " ;fi
	}
	
	Magento()
	{
	clear
	if test -f "app/etc/env.php"; then echo "This is Magento. I got nothin yet ¯\_(ツ)_/¯ " ;fi
	}
	#
pause
	PHP()
	{
	clear
	if test -f "include/connect.php"; then echo "This is PHP. I got nothin yet ¯\_(ツ)_/¯ " ;fi
	}
pause
	HTML()
	{
	clear
	if test -f "index.html"; then echo "This is HTML. I got nothin  ¯\_(ツ)_/¯ " ;fi
	}
pause
 
# function to display menus
show_menus() {
	clear
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~"	
	echo " Which CMS is this?"
	echo 
	echo "~~~~~~~~~~~~~~~~~~~~~~~~~"
	echo " 1. Wordpress"
	echo " 2. Prestashop"
	echo " 3. Joomla"
	echo " 4. Moodle"
	echo " 5. Magento"
	echo " 6. PHP"
	echo " 7. HTML"

}
read_options(){
	local choice
	read -p "Enter choice [ 1 - 7] " choice
	case $choice in
		1) Wordpress ;;
		2) Prestashop ;;
		3) Joomla ;;
		4) Moodle ;;
		5) Magento ;;
		6) PHP ;;
		7) HTML ;;
		*) echo -e "Pick a numero between 1 and 7" && sleep 2
	esac
}
 
# ----------------------------------------------
# Step #3: Trap CTRL+C, CTRL+Z and quit singles
# ----------------------------------------------
#trap '' SIGINT SIGQUIT SIGTSTP
 
# -----------------------------------
# Step #4: Main logic - infinite loop
# ------------------------------------
while true
do
 
	show_menus
	read_options
done
